; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
;src_dir= src_nextion
src_dir = src_crono
default_envs = nodemcuv2

[common]
build_flags = 
	-DPROJECT_VERSION='2.3.0'
	-DUSE_NEXTION=1
	-Dversione=158
lib_deps = 
	/media/progetti_ext/PROJECT/new_libs/topic
	/media/progetti_ext/PROJECT/new_libs/password
	/media/progetti_ext/PROJECT/new_libs/myIP
	knolleary/PubSubClient@^2.8

[env:nodemcuv2-light]
platform = espressif8266
board = d1
framework = arduino
monitor_port = /dev/ttyUSB0
upload_port = /dev/ttyUSB0
monitor_speed = 38400
upload_speed = 921600
lib_deps = 
	${common.lib_deps}
	bblanchon/ArduinoJson@6.21.6
build_flags = 
	${common.build_flags}
	-DESP8266_BUILD=1
	-DDHT_PIN=2
	-DIR_PIN=14

[env:nodemcuv2]
platform = espressif8266
board = d1
framework = arduino
monitor_port = /dev/ttyUSB0
upload_port = /dev/ttyUSB0
monitor_speed = 38400
upload_speed = 921600
lib_deps = 
	${common.lib_deps}
	ESP8266WiFi
	ESP8266HTTPUpdateServer
;	djgrrr/Int64String@^1.1.1
	knolleary/PubSubClient@^2.8
	beegee-tokyo/DHT sensor library for ESPx @ ^1.19
;	crankyoldgit/IRremoteESP8266@^2.8.6
	/media/progetti_ext/PROJECT/new_libs/topic
;	/media/progetti_ext/PROJECT/new_libs/Nextion
	/media/progetti_ext/PROJECT/new_libs/password
	/media/progetti_ext/PROJECT/new_libs/myIP
	bblanchon/ArduinoJson@6.21.6
build_flags = 
	${common.build_flags}
	-DESP8266_BUILD=1
	-DDHT_PIN=2
	-DIR_PIN=14

[env:esp32c3]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 9600
upload_speed = 921600
monitor_port = /dev/ttyACM0
upload_port = /dev/ttyACM0
board_build.partitions = tools/partition.csv
lib_deps = 
	${common.lib_deps}
	HTTPClient
	HTTPUpdate
	WiFi
	djgrrr/Int64String@^1.1.1
	knolleary/PubSubClient@^2.8
	beegee-tokyo/DHT sensor library for ESPx @ ^1.19
	crankyoldgit/IRremoteESP8266@^2.8.6
	/media/progetti_ext/PROJECT/new_libs/topic
;	/media/progetti_ext/PROJECT/new_libs/Nextion
	/media/progetti_ext/PROJECT/new_libs/password
	/media/progetti_ext/PROJECT/new_libs/myIP
	bblanchon/ArduinoJson@6.21.6
build_flags = 
	${common.build_flags}
	-DESP32_BUILD=1
	-DDHT_PIN=4
	-DIR_PIN=10
	-DNEXTION_RX=20
	-DNEXTION_TX=21
	-DNEXTION_USE_HARDWARE_SERIAL=1
	-DCORE_DEBUG_LEVEL=3
	-DBOARD_HAS_PSRAM=0
	-DARDUINO_USB_MODE=1
	-DARDUINO_USB_CDC_ON_BOOT=1
